FROM ubuntu:focal

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Madrid

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y \
    bash-completion man nano \
    python3 python3-pip \
    haskell-platform \
    openjdk-11-jdk

ENV DEBIAN_FRONTEND=

RUN echo "alias ls='ls --color'" >> /root/.bashrc \
    && echo "source /etc/bash_completion" >> /root/.bashrc

WORKDIR /funspel

